server:
  port: 9527
spring:
  application:
    name: rubbish_classification_gateway

eureka:
  instance:
    instance-id: gateway-9572
    prefer-ip-address: true
  client:
    service-url:
      # 单机版配置defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka #设置与eureka server 交互的地址查询服务和注册服务都需要依赖的地址
      #集群配置
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/

#zuul 访问格式http://zuulip:port/微服务名或映射名/资源路径
zuul:
  routes:
    myserver:
      serviceId: RUBBISH-CLASSIFICATION-SERVER #此微服务
      path: /class/** #映射成这样访问
  ignored-services: "*" #这样配置代表所有真实微服务名字禁用
  #ignored-services: rubbish-classification-server #此服务不能再用此名字访问
  prefix: /api #设置公共前缀
  zuul:
    host:
      socket:
        timeout-millis: 60000
  #默认2000
      connect-timeout-millis: 60000

ribbon:
  ReadTimeout: 60000
  # 请求连接超时时间
  ConnectTimeout: 60000
# 断路器超时时间
hystrix:
  command:
   default:
     execution:
      isolation:
        thread:
         timeoutInMilliseconds: 60000


#基本信息描述
info:
  app.name: zp-zuul-9527
  company.name: www.zp.com