server:
  port: 8080

spring:
  application:
    name: rubbish-classification-web  #应用名称
#thymeleaf关闭缓存.
  thymeleaf:
    cache: false
    content-type: text/html
    encoding: UTF-8
    suffix: .html
    prefix: classpath:/templates/

#eureka:
#  client:
#    register-with-eureka: false #false表示不向注册中心注册自己
#    service-url:
#      #defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/  #设置与Eureka Server 交互的地址查询服务和注册服务
#      defaultZone: http://localhost:7001/eureka/,http://localhost.com:7002/eureka/,http://localhost.com:7003/eureka/ #集群版
#  # server:
#  #    enable-self-preservation: false   #关闭自我保护机制 不推荐关闭

